version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 3010:3010
    depends_on:
      - local_mysql
    volumes:
    - .:/usr/src/app

  local_mysql:
    container_name: local_mysql
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "local_backend"
      MYSQL_TCP_PORT: "3306"
    ports:
      - "3306:3306"
volumes: 
 data: {}