name: Prisma Operations

on:
  push:
    branches: [main]
    paths:
      - "./prisma/**/*.*"
  workflow_dispatch:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "yarn"

      - name: Install
        run: yarn install
      - name: Rerun Install
        run: yarn install
        
  migrate:
    runs-on: ubuntu-latest

    needs: install

    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "yarn"

      - name: Install
        run: yarn install

      - run: rm -rf node_modules/.prisma

      - name: Deploy Migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}